### ISSUE TITLE
Rename repo and font names (including internally)

### ISSUE THREAD

**Issue by davelab6** [etunni/Changa#1]
As you can read in https://github.com/vaishnavimurthy/Akaya-Kannada/issues/1 I don't want language or script names in family names, so please rename the repo to `Changa` in https://github.com/etunni/Changa-Arabic/settings and update the font filenames and metadata to simply "Changa" :)

**Comment by etunni** [comment]
Hi,

I can do it today!

Cheers
Edu

**Comment by etunni** [comment]
Done!

**Comment by davelab6** [comment]
Thanks! The PDF source files are not yet included. 

Also, I'm curious why there are 4 glyphs files, not 1 files with the 4 masters as masters? :)

**Comment by etunni** [comment]
Hi Dave,

> Thanks! The PDF source files are not yet included.
> 
> The pdf is not protected an coul be open with adobe illustrator.
> 
> Also, I'm curious why there are 4 glyphs files, not 1 files with the 4 masters as masters? :)
> 
> If you want I can upload the source with two masters. ;)

Cheers,
Edu

**Comment by davelab6** [comment]
> The pdf is not protected an coul be open with adobe illustrator.

I thought they were made with InDesign though, since they are multi-page documents?

> If you want I can upload the source with two masters. ;)

Its best to have the sources in the 'real' form that you actually use yourself to maintain the project; I'm curious why you don't have a single file for all masters, though :)
